/**
 * System notifications.
 *
 * Every notification is derived deterministically from live registry data —
 * there is no separate notifications table and nothing is generated by AI.
 * Read state is per-browser (localStorage) since notifications are ephemeral
 * views over the current state of the registry.
 */
import { priorityBand } from "@/lib/cases";
import { scanSystemConflicts, type ConflictScanInput } from "@/lib/conflicts";
import type { DashboardData } from "@/lib/dashboard";
import type { AuditLogEntry } from "@/lib/audit";

export type NotificationKind =
  "conflict" | "unscheduled_case" | "judge_capacity" | "simulation_pending";

export type NotificationTarget =
  | { route: "/conflicts" }
  | { route: "/what-if-simulation" }
  | { route: "/cases/$caseId"; caseId: string }
  | { route: "/judges/$judgeId"; judgeId: string };

export type SystemNotification = {
  id: string;
  kind: NotificationKind;
  title: string;
  detail: string;
  /** Sort/priority weight — lower sorts first. */
  rank: number;
  target: NotificationTarget;
};

export const notificationKindLabel: Record<NotificationKind, string> = {
  conflict: "Conflict Detection",
  unscheduled_case: "Priority Score",
  judge_capacity: "Judge workload",
  simulation_pending: "What-If Simulation",
};

/* ------------------------------------------------------------ preferences */

const THRESHOLD_KEY = "notifications.unscheduledThresholdDays";
const SEEN_KEY = "notifications.seenIds";

export const UNSCHEDULED_THRESHOLD_OPTIONS = [3, 7, 14, 30];
export const DEFAULT_UNSCHEDULED_THRESHOLD_DAYS = 7;

/** Judges at or above this share of their workload cap are "nearing capacity". */
export const CAPACITY_WARNING_RATIO = 0.8;

export function readUnscheduledThreshold(): number {
  if (typeof window === "undefined") return DEFAULT_UNSCHEDULED_THRESHOLD_DAYS;
  const raw = Number(window.localStorage.getItem(THRESHOLD_KEY));
  return Number.isFinite(raw) && raw > 0 ? raw : DEFAULT_UNSCHEDULED_THRESHOLD_DAYS;
}

export function writeUnscheduledThreshold(days: number) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(THRESHOLD_KEY, String(days));
}

export function readSeenIds(): string[] {
  if (typeof window === "undefined") return [];
  try {
    const parsed = JSON.parse(window.localStorage.getItem(SEEN_KEY) ?? "[]");
    return Array.isArray(parsed) ? parsed.filter((v): v is string => typeof v === "string") : [];
  } catch {
    return [];
  }
}

export function writeSeenIds(ids: string[]) {
  if (typeof window === "undefined") return;
  // Cap the stored list so it cannot grow without bound.
  window.localStorage.setItem(SEEN_KEY, JSON.stringify(ids.slice(-500)));
}

/* -------------------------------------------------------------- derivation */

const daysSince = (iso: string) => {
  const then = new Date(iso).getTime();
  if (Number.isNaN(then)) return 0;
  return Math.max(0, Math.floor((Date.now() - then) / 86_400_000));
};

const SIM_RUN = "ran what-if simulation";
const SIM_APPLIED = "applied what-if simulation";

/**
 * What-If Simulations that were run but never committed. A run entry is
 * considered resolved when a later "applied" entry exists for the same
 * judge + date target.
 */
export function pendingSimulations(entries: AuditLogEntry[]): SystemNotification[] {
  const runs = entries.filter((e) => e.action.toLowerCase().startsWith(SIM_RUN));
  const applies = entries.filter((e) => e.action.toLowerCase().startsWith(SIM_APPLIED));

  return runs
    .filter(
      (run) =>
        !applies.some(
          (a) =>
            a.entity_affected === run.entity_affected &&
            new Date(a.timestamp).getTime() >= new Date(run.timestamp).getTime(),
        ),
    )
    .slice(0, 5)
    .map((run) => ({
      id: `simulation:${run.id}`,
      kind: "simulation_pending" as const,
      title: "What-If Simulation not applied",
      detail: `${run.action.replace(/^Ran What-If Simulation — /i, "")} — run by ${run.userName}, never committed.`,
      rank: 3,
      target: { route: "/what-if-simulation" as const },
    }));
}

export function buildNotifications(params: {
  dashboard: DashboardData;
  conflictInput: ConflictScanInput;
  auditEntries: AuditLogEntry[];
  thresholdDays: number;
}): SystemNotification[] {
  const { dashboard, conflictInput, auditEntries, thresholdDays } = params;
  const items: SystemNotification[] = [];

  /* 1 — conflicts currently flagged by the deterministic scanner */
  const conflicts = scanSystemConflicts(conflictInput);
  for (const c of conflicts) {
    items.push({
      id: `conflict:${c.scheduleId}:${c.kind}`,
      kind: "conflict",
      title: c.title,
      detail: `${c.caseNumber} · ${c.slotLabel}`,
      rank: c.severity === "blocking" ? 0 : 1,
      target: { route: "/conflicts" },
    });
  }

  /* 2 — high-priority cases still unscheduled after the configured window */
  const activeSchedules = dashboard.schedules.filter(
    (s) => s.status === "proposed" || s.status === "confirmed",
  );
  const scheduledCaseIds = new Set(activeSchedules.map((s) => s.case_id));
  for (const c of dashboard.cases) {
    if (c.status === "disposed" || scheduledCaseIds.has(c.id)) continue;
    if (priorityBand(c.priority_score) !== "high") continue;
    const waiting = daysSince(c.created_at);
    if (waiting < thresholdDays) continue;
    items.push({
      id: `case:${c.id}`,
      kind: "unscheduled_case",
      title: `${c.case_number} unscheduled for ${waiting} day${waiting === 1 ? "" : "s"}`,
      detail: `High Priority Score (${Math.round(c.priority_score ?? 0)}) with no active listing.`,
      rank: 2,
      target: { route: "/cases/$caseId", caseId: c.id },
    });
  }

  /* 3 — judges nearing their workload capacity */
  for (const judge of dashboard.judges) {
    const hearings = activeSchedules.filter((s) => s.judge_id === judge.id).length;
    const cap = Math.max(1, dashboard.maxJudgeWorkload);
    if (hearings / cap < CAPACITY_WARNING_RATIO) continue;
    items.push({
      id: `judge:${judge.id}`,
      kind: "judge_capacity",
      title:
        hearings >= cap
          ? `${judge.name} is at workload capacity`
          : `${judge.name} is nearing workload capacity`,
      detail: `${hearings} of ${cap} active hearings (${Math.round((hearings / cap) * 100)}%).`,
      rank: hearings >= cap ? 1 : 2,
      target: { route: "/judges/$judgeId", judgeId: judge.id },
    });
  }

  /* 4 — What-If Simulations run but never applied */
  items.push(...pendingSimulations(auditEntries));

  return items.sort((a, b) => a.rank - b.rank || a.title.localeCompare(b.title));
}
